variables:
  GOPATH: "$CI_PROJECT_DIR/.go"

cache:
  paths:
    - .go/pkg/mod

build:
  stage: build
  image: golang:1.11.5
  script:
    - make install
  artifacts:
    paths:
      - "$GOPATH/bin/xrnd"
      - "$GOPATH/bin/xrncli"

test:
  image: golang:1.11.5
  script:
    - GOFLAGS=-cover make test
  after_script:
    - make test_cover
    - bash <(curl -s https://codecov.io/bash) -f coverage.txt -t $CODECOV_TOKEN

#integration_test:
#  image: golang:1.11.5
#  services:
#    - mdillon/postgis:11
#  script:
#    - GOFLAGS=-cover make test
#  coverage: '/\d+.\d+% of statements/'
#  artifacts:
#    reports:
#      junit: "TEST_*.xml"

#lint:
#  image: golang:1.11.5
#  script:
#    - make lint
